version: "3"

services:
  server:
    build: QTcpServer-Example/
    command: ./QTcpServer-Example
    ports:
      - 4242:4242

  client:
    build: QTcpClient-Example/
    #environment:
    #  - IP_ADDRESS='192.168.239.192'
    command: ./QTcpClient-Example
    network_mode: host
    depends_on:
      - server