version: "3"

services:
  server:
    build: QTcpServer-Example/
    command: ./QTcpServer-Example
    ports:
      - 4242:4242

  client:
    build:
      context: QTcpClient-Example/
      args:
        - IP_ADDRESS=${IP_ADDRESS}
    command: ./QTcpClient-Example
    network_mode: host
    depends_on:
      - server